### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [nsdrozario/guitar-amp#21]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Guitar DSPs section](https://github.com/forart/HyMPS/blob/main/GuitarDSPs.md)), can you please set licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/nsdrozario/guitar-amp/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/nsdrozario/guitar-amp/?label=LICENSE)

...maybe is a GH setup issue ?

Thanks in advance.

**Comment by nsdrozario** [comment]
Hello,
Thank you for your interest! 
I have changed the LICENSE file to only include the MIT license text. However, GitHub has not picked up on this yet (so neither has most badge services). I think it'll take a bit of time for GitHub to update the repository's metadata. I will check on this issue periodically to make sure the change happens.

**Comment by forart** [comment]
Hi there, thanks for your corrections.

Anyway probably GH needs a license file [like this](https://github.com/apohl79/audiogridder/blob/master/COPYING) to match correctly.

Hope that helps.

Thanks again for your work.

**Comment by nsdrozario** [comment]
Hello again,
Thanks for the advice. It turns out that the 3rd party license file was still being picked up by GitHub (their Licensee tool more specifically) and the way to fix that was to change the name of the license file and to move the 3rd party license file out of the root directory. It seems like the correct badge is being generated now too. Thank you!
